services:
  redis:
    image: redis:7-alpine
    container_name: multi-tenant-nest-redis
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
